=== thecodingmachine/mouf-legacy/direct/xsd/packages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">


    <xsd:complexType name="Package">
    	<xsd:sequence>
    		<xsd:element ref="displayName" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="shortDescription" type="xsd:string"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="docUrl" type="xsd:string" maxOccurs="1"
    			minOccurs="0">
    		</xsd:element>
    		<xsd:element name="doc" type="Doc" maxOccurs="1"
    			minOccurs="0">
    		</xsd:element>
    		<xsd:element name="logo" type="xsd:anyURI" maxOccurs="1"
    			minOccurs="0">
    		</xsd:element>
    		<xsd:element name="dependencies" type="Dependencies"
    			maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="requires" type="RequireList"
    			maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="adminRequires" type="RequireList"
    			maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="install" type="InstallList" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:simpleType name="DisplayName">
    	<xsd:restriction base="xsd:string"></xsd:restriction>
    </xsd:simpleType>


    <xsd:element name="displayName" type="DisplayName"></xsd:element>

    <xsd:element name="package" type="Package"></xsd:element>


    <xsd:complexType name="Doc">
    	<xsd:sequence>
    		<xsd:element name="page" type="DocPage" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="root" type="xsd:string"></xsd:attribute>
    </xsd:complexType>



    <xsd:complexType name="DocPage">
    	<xsd:sequence>
    		<xsd:element name="page" type="DocPage" maxOccurs="unbounded"
    			minOccurs="0">
    		</xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="title" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="url" type="xsd:anyURI" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="Dependency">
    	<xsd:sequence>
    		<xsd:element name="group" type="xsd:string"></xsd:element>
    		<xsd:element name="name" type="xsd:string"></xsd:element>
    		<xsd:element name="version" type="xsd:string"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Dependencies">
    	<xsd:sequence>
    		<xsd:element name="dependency" type="Dependency" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="RequireList">
    	<xsd:sequence>
    		<xsd:element name="require" type="xsd:string" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="InstallList">
    	<xsd:choice maxOccurs="unbounded" minOccurs="0">
    		<xsd:element name="url" type="xsd:string"
    			maxOccurs="unbounded" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="file" type="xsd:string" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:choice>
    </xsd:complexType>
</xsd:schema>

=== thecodingmachine/mouf-legacy/html/utils/i18nweblibrarysupport/1.0/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="http://xsd.mouf-php.com/packages.xsd">
	<displayName>I18N Weblibrary Support</displayName>
	<shortDescription>TODO</shortDescription>
	<logo>logo.png</logo>
	<dependencies>
		<dependency>
			<group>html/utils</group>
			<name>weblibrarymanager</name>
			<version>>=1.0</version>
		</dependency>
		<dependency>
			<group>utils/i18n</group>
			<name>fine</name>
			<version>>=2.2</version>
		</dependency>
	</dependencies>
	<requires>
		<require>I18nWebLibrary.php</require>
	</requires>
</package>

=== thecodingmachine/mouf-legacy/utils/mailer/mail-interface/1.1/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="http://xsd.mouf-php.com/packages.xsd">
	<displayName>Mail Interface</displayName>
	<shortDescription>This package contains interfaces and classes describing mails. It also contains the MailerService interface that should be implemented by any service that can send mails. You should use a package implementing this interface (like the SmtpMailer package.</shortDescription>
	<docUrl></docUrl>
	<doc>
		<page title="Introduction to Mouf's mail architecture" url="index.html" />
	</doc>
	<logo>logo.png</logo>
	
	<dependencies>
		<dependency>
			<group>html/utils</group>
			<name>emogrifier</name>
			<version>2011-10-26</version>
		</dependency>
	</dependencies>
	
	<requires>
		<require>MailAttachmentInterface.php</require>
		<require>MailAttachment.php</require>
		<require>MailAddressInterface.php</require>
		<require>MailAddress.php</require>
		<require>MailInterface.php</require>
		<require>Mail.php</require>
		<require>MailServiceInterface.php</require>
	</requires>
	
</package>

=== thecodingmachine/mouf-legacy/utils/mailer/db-mail-service/1.0/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="http://xsd.mouf-php.com/packages.xsd">
	<displayName>DB Mail Service</displayName>
	<shortDescription>This package contains a mailer that does not send any mail! Instead, it stores the mail to
	be sent in a database "mails" table. The DB mailer can later forward the mail to a real mailer that will indeed
	send the mail.</shortDescription>
	<docUrl></docUrl>
	<doc>
		<page title="Storing sent mails using the DB Mail Service" url="dbmailservice.html" />
	</doc>	
	<logo>logo.png</logo>
	
	<dependencies>
		<dependency>
			<group>utils/common</group>
			<name>mouf_helpers</name>
			<version>>=1.0</version>
		</dependency>
		<dependency>
			<group>utils/mailer</group>
			<name>mail-interface</name>
			<version>>=1.0</version>
		</dependency>
		<dependency>
			<group>utils/mailer</group>
			<name>mail-interface</name>
			<version>>=1.0</version>
			<scope>admin</scope>
		</dependency>
		<dependency>
			<group>utils/log</group>
			<name>errorlog_logger</name>
			<version>>=1.0</version>
		</dependency>
		<dependency>
			<group>database</group>
			<name>dbconnection</name>
			<version>>=1.0</version>
		</dependency>
	</dependencies>
	<requires>
		<require>DBMailInterface.php</require>
		<require>DBMail.php</require>
		<require>DBMailServiceException.php</require>
		<require>DBMailService.php</require>
	</requires>
	<adminRequires>
		<require>controllers/DBMailServiceInstallController.php</require>
		<require>controllers/DBMailServiceListController.php</require>
		<require>DBMailInterface.php</require>
		<require>DBMail.php</require>
		<require>DBMailServiceAdmin.php</require>
	</adminRequires>
	<install>
		<url>mouf/dbmailserviceinstall/</url>
	</install>
</package>

=== thecodingmachine/mouf-legacy/utils/mailer/blacklist-mail-service/1.0/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="http://xsd.mouf-php.com/packages.xsd">
	<displayName>Blacklist Mail Service</displayName>
	<shortDescription>This package contains a mailer that does not really send any mail! Instead, it modifies
	your mail to add a "unsubscribe this mailing list" link at the end of your mail. This will allow
	your users to unsubscribe from the mailing list. Any attempt to send a mail to this user later
	will be rejected.</shortDescription>
	<docUrl></docUrl>
	<doc>
		<page title="Manage mailing list unsubscribe using the BlackList Mail Service" url="blacklistmailservice.html" />
	</doc>	
	<logo>logo.png</logo>
	
	<dependencies>
		<dependency>
			<group>utils/common</group>
			<name>mouf_helpers</name>
			<version>>=1.0</version>
		</dependency>
		<dependency>
			<group>utils/mailer</group>
			<name>db-mail-service</name>
			<version>>=1.0</version>
		</dependency>
		<dependency>
			<group>utils/mailer</group>
			<name>mail-interface</name>
			<version>>=1.0</version>
			<scope>admin</scope>
		</dependency>
		<dependency>
			<group>utils/log</group>
			<name>errorlog_logger</name>
			<version>>=1.0</version>
		</dependency>
		<dependency>
			<group>database</group>
			<name>dbconnection</name>
			<version>>=1.0</version>
		</dependency>
		<dependency>
			<group>html/template</group>
			<name>BaseTemplate</name>
			<version>>=1.0</version>
		</dependency>
		<dependency>
			<group>utils/i18n</group>
			<name>fine</name>
			<version>>=2.1</version>
		</dependency>
	</dependencies>
	<requires>
		<require>BlackListMail.php</require>
		<require>BlackListMailServiceException.php</require>
		<require>BlackListMailService.php</require>
	</requires>
	<adminRequires>
		<require>admin/controllers/BlackListMailServiceInstallController.php</require>
		<require>admin/controllers/BlackListMailServiceListController.php</require>
		<require>admin/BlackListMailServiceAdmin.php</require>
	</adminRequires>
	<install>
		<url>mouf/blacklistmailserviceinstall/</url>
	</install>
</package>

=== thecodingmachine/mouf-legacy/html/widgets/evolugrid/1.0/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="http://xsd.mouf-php.com/packages.xsd">
	<displayName>EvoluGrid Widget</displayName>
	<shortDescription>This package contains the EvoluGrid widget. This is an HTML/Ajax datagrid that can be used to display data. It's main difference with other datagrids is that you can chage the set of columns dynamically depending on the paginated results you are looking at.</shortDescription>
	<docUrl></docUrl>
	<dependencies>
		<dependency>
			<group>html</group>
			<name>htmlelement</name>
			<version>&gt;=1.0</version>
		</dependency>
	</dependencies>
	<requires>
		<require>src/Mouf/Html/Widgets/EvoluGrid/EvoluColumn.php</require>
		<require>src/Mouf/Html/Widgets/EvoluGrid/EvoluGrid.php</require>
	</requires>
	<install>
		<file>install.php</file>
	</install>
</package>
